"""Module for enforcing fast execution guardrails on LLM-generated code patches.

This module validates generated blocks against simple structural properties (such as size,
emptiness, and duplication) without executing heavy syntax analysis or external processes.
"""

from typing import Tuple


def is_empty_patch(patch_code: str) -> bool:
    """Checks if the generated patch code block is empty or whitespace-only.

    Args:
        patch_code: The cleaned code string received from the LLM parser layer.

    Returns:
        True if the patch lacks any executable content, False otherwise.
    """
    return not patch_code or not patch_code.strip()


def is_same_patch(original_code: str, patch_code: str) -> bool:
    """Checks if the generated patch is identical to the original block.

    This prevents the pipeline from processing redundant operational updates that yield
    no functional delta.

    Args:
        original_code: The original raw code block extracted from the file.
        patch_code: The cleaned code string received from the LLM parser layer.

    Returns:
        True if both blocks are functionally identical after normalization, False otherwise.
    """
    return original_code.strip() == patch_code.strip()


def is_patch_too_large(original_code: str, patch_code: str) -> bool:
    """Checks if the patch contains more than two extra lines compared to the original code.

    This serves as a protective guardrail against LLM structural drifts, conversational text
    leakage, or accidental generation of entire file architectures.

    Args:
        original_code: The original raw code block extracted from the file.
        patch_code: The cleaned code string received from the LLM parser layer.

    Returns:
        True if the patch code line count exceeds original code line count by more than 2.
    """
    original_lines = original_code.splitlines()
    patch_lines = patch_code.splitlines()

    return len(patch_lines) > (len(original_lines) + 2)


def validate_generated_patch(original_code: str, patch_code: str) -> Tuple[bool, str]:
    """Orchestrates all local guardrail rules sequentially to validate an LLM patch.

    Args:
        original_code: The original raw code block extracted from the target file.
        patch_code: The cleaned, parsed code string generated by the LLM.

    Returns:
        A tuple containing (is_valid, reason). If valid, returns (True, "Valid patch").
        If a guardrail rule triggers a rejection, returns (False, descriptive_reason_string).
    """
    if is_empty_patch(patch_code):
        return False, "Rejected: Generated patch is empty or whitespace-only."

    if is_same_patch(original_code, patch_code):
        return False, "Rejected: Generated patch is identical to the original code block."

    if is_patch_too_large(original_code, patch_code):
        return False, "Rejected: Generated patch size is too large (exceeds original by more than 2 lines)."

    return True, "Valid patch"