"""Runner module for executing the Ruff linter tool as a sub-process.

Supports targeted file array parsing or single structural directory context paths.
"""

import json
import subprocess
from utils.logger import get_logger

logger = get_logger(__name__)


def run_ruff(target: str | list[str]) -> list[dict]:
    """Execute Ruff check over target paths and retrieve parsed diagnostic JSON arrays.

    Args:
        target (str | list[str]): Absolute target directory path, single module file, 
                                  or a list of explicit file path vectors.

    Returns:
        list[dict]: Collected structural issue entities generated by the runner.
    """
    logger.info("[✓] Running Ruff...")

    # Assemble base command parameters
    command = [
        "ruff",
        "check",
        "--output-format=json",
    ]

    # Handle structural input variance safely to mitigate character overflow limits
    if isinstance(target, str):
        command.append(target)
    else:
        command.extend(target)

    result = subprocess.run(
        command,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace"
    )

    # Ruff execution tracking lifecycle check: 0 (No findings), 1 (Findings identified)
    if result.returncode not in (0, 1):
        logger.error("❌ Ruff execution failed with return code %d.", result.returncode)
        if result.stderr.strip():
            logger.error("Ruff Stderr Context:\n%s", result.stderr)
        return []

    logger.info("✔ Ruff analysis completed.")

    if not result.stdout.strip():
        return []

    try:
        parsed_output = json.loads(result.stdout)
        # Handle structural variance if output format behaves as wrapped dict frames
        if isinstance(parsed_output, dict) and "results" in parsed_output:
            return parsed_output["results"]
        return parsed_output if isinstance(parsed_output, list) else []

    except json.JSONDecodeError:
        logger.exception("❌ Failed to decode Ruff JSON stdout output.")
        logger.debug("Raw unparsed stdout: %s", result.stdout)
        return []